// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientDashboardAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ClientDashboardAPI.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Company")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "123 Test Ave",
                            Company = "TestCo",
                            Email = "test@example.com",
                            Name = "Test Client"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "456 Sample Blvd",
                            Company = "SecondCo",
                            Email = "second@example.com",
                            Name = "Second Client"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Address = "1 Alpha Way",
                            Company = "Alpha Inc",
                            Email = "contact@alpha.com",
                            Name = "Alpha Inc"
                        },
                        new
                        {
                            Id = 4,
                            Active = false,
                            Address = "42 Beta St",
                            Company = "Beta Corporation",
                            Email = "info@beta.com",
                            Name = "Beta Corp"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Address = "99 Gamma Circle",
                            Company = "Gamma LLC",
                            Email = "support@gamma.com",
                            Name = "Gamma LLC"
                        },
                        new
                        {
                            Id = 6,
                            Active = false,
                            Address = "67 Delta Rd",
                            Company = "Delta Co",
                            Email = "hello@delta.com",
                            Name = "Delta Co"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Address = "8 Epsilon Pkwy",
                            Company = "Epsilon Ltd",
                            Email = "office@epsilon.com",
                            Name = "Epsilon Ltd"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Address = "77 Zeta Ln",
                            Company = "Zeta Group",
                            Email = "zeta@group.org",
                            Name = "Zeta Group"
                        },
                        new
                        {
                            Id = 9,
                            Active = false,
                            Address = "34 Eta Dr",
                            Company = "Eta Agency",
                            Email = "contact@etaagency.com",
                            Name = "Eta Agency"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Address = "12 Theta Ct",
                            Company = "Theta Enterprises",
                            Email = "theta@enterprises.net",
                            Name = "Theta Enterprises"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Address = "90 Iota Cres",
                            Company = "Iota Partners",
                            Email = "info@iotapartners.com",
                            Name = "Iota Partners"
                        },
                        new
                        {
                            Id = 12,
                            Active = false,
                            Address = "4 Kappa Blvd",
                            Company = "Kappa Services",
                            Email = "admin@kappaservices.com",
                            Name = "Kappa Services"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Address = "6 Lambda St",
                            Company = "Lambda Systems",
                            Email = "lambda@systems.biz",
                            Name = "Lambda Systems"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Address = "22 Mu Rd",
                            Company = "Mu Logistics",
                            Email = "mu@logistics.org",
                            Name = "Mu Logistics"
                        },
                        new
                        {
                            Id = 15,
                            Active = false,
                            Address = "100 Nu Tech Dr",
                            Company = "Nu Technologies",
                            Email = "team@nu.tech",
                            Name = "Nu Technologies"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Address = "59 Xi Ave",
                            Company = "Xi Solutions",
                            Email = "xi@solutions.dev",
                            Name = "Xi Solutions"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Address = "14 Omicron Way",
                            Company = "Omicron Industries",
                            Email = "omicron@industries.net",
                            Name = "Omicron Industries"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Address = "88 Pi Park",
                            Company = "Pi Innovations",
                            Email = "hello@piinnovations.com",
                            Name = "Pi Innovations"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Address = "21 Rho Dr",
                            Company = "Rho Labs",
                            Email = "rho@labs.tech",
                            Name = "Rho Labs"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            Address = "5 Sigma Ln",
                            Company = "Sigma Ventures",
                            Email = "sigma@ventures.io",
                            Name = "Sigma Ventures"
                        });
                });

            modelBuilder.Entity("ClientDashboardAPI.Models.PhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FormattedNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_rawPhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RawPhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("PhoneNumbers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            FormattedNumber = "(516) 913-4354",
                            _rawPhoneNumber = "5169134354"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 1,
                            FormattedNumber = "(810) 810-5096",
                            _rawPhoneNumber = "8108105096"
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 1,
                            FormattedNumber = "(309) 786-8003",
                            _rawPhoneNumber = "3097868003"
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 1,
                            FormattedNumber = "(215) 633-2089",
                            _rawPhoneNumber = "2156332089"
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 2,
                            FormattedNumber = "(746) 731-8429",
                            _rawPhoneNumber = "7467318429"
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 2,
                            FormattedNumber = "(238) 886-1541",
                            _rawPhoneNumber = "2388861541"
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 3,
                            FormattedNumber = "(956) 415-9515",
                            _rawPhoneNumber = "9564159515"
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 3,
                            FormattedNumber = "(694) 136-9631",
                            _rawPhoneNumber = "6941369631"
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 6,
                            FormattedNumber = "(133) 313-2881",
                            _rawPhoneNumber = "1333132881"
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 6,
                            FormattedNumber = "(192) 843-1901",
                            _rawPhoneNumber = "1928431901"
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 6,
                            FormattedNumber = "(274) 443-6658",
                            _rawPhoneNumber = "2744436658"
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 8,
                            FormattedNumber = "(220) 407-6727",
                            _rawPhoneNumber = "2204076727"
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 10,
                            FormattedNumber = "(222) 575-6115",
                            _rawPhoneNumber = "2225756115"
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 11,
                            FormattedNumber = "(530) 481-9521",
                            _rawPhoneNumber = "5304819521"
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 11,
                            FormattedNumber = "(804) 841-3297",
                            _rawPhoneNumber = "8048413297"
                        },
                        new
                        {
                            Id = 16,
                            ClientId = 11,
                            FormattedNumber = "(673) 997-5545",
                            _rawPhoneNumber = "6739975545"
                        },
                        new
                        {
                            Id = 17,
                            ClientId = 12,
                            FormattedNumber = "(292) 796-3892",
                            _rawPhoneNumber = "2927963892"
                        },
                        new
                        {
                            Id = 18,
                            ClientId = 12,
                            FormattedNumber = "(831) 493-1097",
                            _rawPhoneNumber = "8314931097"
                        },
                        new
                        {
                            Id = 19,
                            ClientId = 14,
                            FormattedNumber = "(621) 633-6470",
                            _rawPhoneNumber = "6216336470"
                        },
                        new
                        {
                            Id = 20,
                            ClientId = 14,
                            FormattedNumber = "(482) 221-5583",
                            _rawPhoneNumber = "4822215583"
                        },
                        new
                        {
                            Id = 21,
                            ClientId = 14,
                            FormattedNumber = "(542) 877-4014",
                            _rawPhoneNumber = "5428774014"
                        },
                        new
                        {
                            Id = 22,
                            ClientId = 15,
                            FormattedNumber = "(430) 224-7502",
                            _rawPhoneNumber = "4302247502"
                        },
                        new
                        {
                            Id = 23,
                            ClientId = 15,
                            FormattedNumber = "(287) 676-4409",
                            _rawPhoneNumber = "2876764409"
                        },
                        new
                        {
                            Id = 24,
                            ClientId = 17,
                            FormattedNumber = "(170) 285-2523",
                            _rawPhoneNumber = "1702852523"
                        },
                        new
                        {
                            Id = 25,
                            ClientId = 18,
                            FormattedNumber = "(984) 522-6675",
                            _rawPhoneNumber = "9845226675"
                        },
                        new
                        {
                            Id = 26,
                            ClientId = 20,
                            FormattedNumber = "(132) 816-5431",
                            _rawPhoneNumber = "1328165431"
                        },
                        new
                        {
                            Id = 27,
                            ClientId = 20,
                            FormattedNumber = "(768) 577-3949",
                            _rawPhoneNumber = "7685773949"
                        },
                        new
                        {
                            Id = 28,
                            ClientId = 20,
                            FormattedNumber = "(262) 456-6803",
                            _rawPhoneNumber = "2624566803"
                        },
                        new
                        {
                            Id = 29,
                            ClientId = 20,
                            FormattedNumber = "(886) 379-3203",
                            _rawPhoneNumber = "8863793203"
                        });
                });

            modelBuilder.Entity("ClientDashboardAPI.Models.PhoneNumber", b =>
                {
                    b.HasOne("ClientDashboardAPI.Models.Client", "Client")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ClientDashboardAPI.Models.Client", b =>
                {
                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
